version: '3'
services:
  app:
    container_name: fibonacci_web_api
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - postgres
    networks:
      - fullstack

  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      - DB_HOST=postgres-emma-8612.aivencloud.com
      - DB_DRIVER=postgres
      - DB_USER=avnadmin
      - DB_PASSWORD=ohx89khk1wmr6d2o
      - DB_NAME=defaultdb
      - DB_PORT=15741
      - SSLMODE=require
    ports:
      - '15741:15741'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - fullstack

volumes:
  api:
  database_postgres:

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge
